<template>
  <div class="fontToImg">
    <p>
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
      plumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliilplumliil
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  setup() {
    return {};
  },
});
</script>

<style scoped>
.fontToImg {
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
}
p {
  border: 1px solid red;
  width: 600px;
  height: 600px;
  color: aliceblue;
  margin-top: 100px;
  font-size: 16px;
  background-image: url("./plum.png");
  background-position: 30% 30%;
  background-repeat: no-repeat;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
</style>
